/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import uniformidad.PruebaChiCuadrado;
import uniformidad.PruebaKolmogorovSmirnov;

/**
 *
 * @author jsnar
 */
public class VistaPruebasUniformidad extends javax.swing.JPanel {

    public static DefaultTableModel modeloTablaPruebaChiCuadrado;
    public static DefaultTableModel modeloTablaPruebaKolmogorovSmirnov;
    /**
     * Creates new form VistaPruebasUniformidad
     */
    public VistaPruebasUniformidad() {
        modeloTablaPruebaChiCuadrado = new DefaultTableModel();
        modeloTablaPruebaChiCuadrado.addColumn("Rango");
        modeloTablaPruebaChiCuadrado.addColumn("FO");
        modeloTablaPruebaChiCuadrado.addColumn("FE");
        modeloTablaPruebaChiCuadrado.addColumn("X2 Calc");
        
        modeloTablaPruebaKolmogorovSmirnov = new DefaultTableModel();
        modeloTablaPruebaKolmogorovSmirnov.addColumn("Rango");
        modeloTablaPruebaKolmogorovSmirnov.addColumn("FO");
        modeloTablaPruebaKolmogorovSmirnov.addColumn("FOA");
        modeloTablaPruebaKolmogorovSmirnov.addColumn("POA");
        modeloTablaPruebaKolmogorovSmirnov.addColumn("PEA");
        modeloTablaPruebaKolmogorovSmirnov.addColumn("| PEA - POA |");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPruebaChiCuadrado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonEjecutarPruebaChiCuadrado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPruebaKolmogorovSmirnov = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        botonEjecutarPruebaKolmogorvSmirnov = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoResultadoKolmogorovSmirnov = new javax.swing.JLabel();
        campoResultadoChiCuadrado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        tablaPruebaChiCuadrado.setModel(modeloTablaPruebaChiCuadrado);
        jScrollPane1.setViewportView(tablaPruebaChiCuadrado);
        if (tablaPruebaChiCuadrado.getColumnModel().getColumnCount() > 0) {
            tablaPruebaChiCuadrado.getColumnModel().getColumn(0).setResizable(false);
            tablaPruebaChiCuadrado.getColumnModel().getColumn(1).setResizable(false);
            tablaPruebaChiCuadrado.getColumnModel().getColumn(2).setResizable(false);
            tablaPruebaChiCuadrado.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("Prueba Chi-Cuadrado");

        botonEjecutarPruebaChiCuadrado.setText("Ejecutar");
        botonEjecutarPruebaChiCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjecutarPruebaChiCuadradoActionPerformed(evt);
            }
        });

        tablaPruebaKolmogorovSmirnov.setModel(modeloTablaPruebaKolmogorovSmirnov);
        jScrollPane2.setViewportView(tablaPruebaKolmogorovSmirnov);
        if (tablaPruebaKolmogorovSmirnov.getColumnModel().getColumnCount() > 0) {
            tablaPruebaKolmogorovSmirnov.getColumnModel().getColumn(0).setResizable(false);
            tablaPruebaKolmogorovSmirnov.getColumnModel().getColumn(1).setResizable(false);
            tablaPruebaKolmogorovSmirnov.getColumnModel().getColumn(2).setResizable(false);
            tablaPruebaKolmogorovSmirnov.getColumnModel().getColumn(3).setResizable(false);
            tablaPruebaKolmogorovSmirnov.getColumnModel().getColumn(4).setResizable(false);
            tablaPruebaKolmogorovSmirnov.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setText("Prueba Kolmogorov -Smirnov");

        botonEjecutarPruebaKolmogorvSmirnov.setText("Ejecutar");
        botonEjecutarPruebaKolmogorvSmirnov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjecutarPruebaKolmogorvSmirnovActionPerformed(evt);
            }
        });

        jLabel3.setText("Resultado:");

        campoResultadoKolmogorovSmirnov.setText("Resultado:");

        campoResultadoChiCuadrado.setText(" ");

        jLabel6.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(botonEjecutarPruebaKolmogorvSmirnov)
                                .addGap(18, 18, 18)
                                .addComponent(campoResultadoKolmogorovSmirnov)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(botonEjecutarPruebaChiCuadrado)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoResultadoChiCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botonEjecutarPruebaChiCuadrado)
                    .addComponent(jLabel3)
                    .addComponent(campoResultadoChiCuadrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(botonEjecutarPruebaKolmogorvSmirnov)
                    .addComponent(campoResultadoKolmogorovSmirnov)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEjecutarPruebaKolmogorvSmirnovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjecutarPruebaKolmogorvSmirnovActionPerformed
        PruebaKolmogorovSmirnov pruebaKolmogorovSmirnov = new PruebaKolmogorovSmirnov();
        boolean resultado = pruebaKolmogorovSmirnov.ejecutarPrueba();
        if(resultado) {
            campoResultadoKolmogorovSmirnov.setText("Tienen distribución uniforme.");
        } else {
            campoResultadoKolmogorovSmirnov.setText("No tienen distribución uniforme.");
        }
    }//GEN-LAST:event_botonEjecutarPruebaKolmogorvSmirnovActionPerformed

    private void botonEjecutarPruebaChiCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjecutarPruebaChiCuadradoActionPerformed
        PruebaChiCuadrado pruebaChiCuadrado = new PruebaChiCuadrado();
        boolean resultado = pruebaChiCuadrado.ejecutarPrueba();
        if(resultado) {
            campoResultadoChiCuadrado.setText("Tienen distribución uniforme.");
        } else {
            campoResultadoChiCuadrado.setText("No tienen distribución uniforme.");
        }
    }//GEN-LAST:event_botonEjecutarPruebaChiCuadradoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEjecutarPruebaChiCuadrado;
    private javax.swing.JButton botonEjecutarPruebaKolmogorvSmirnov;
    private javax.swing.JLabel campoResultadoChiCuadrado;
    private javax.swing.JLabel campoResultadoKolmogorovSmirnov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tablaPruebaChiCuadrado;
    private javax.swing.JTable tablaPruebaKolmogorovSmirnov;
    // End of variables declaration//GEN-END:variables
}
